export const typeMatchup = {
    "Normal": { "Rock": 0.5, "Ghost": 0, "Steel": 0.5, "Normal": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Dragon": 1, "Dark": 1, "Fairy": 1 },
    "Fire": { "Grass": 2, "Water": 0.5, "Ice": 2, "Bug": 2, "Rock": 0.5, "Fire": 1, "Dragon": 1, "Steel": 1, "Normal": 1, "Electric": 1, "Grass": 2, "Fire": 1, "Water": 1, "Ice": 2, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 2, "Dragon": 1, "Dark": 1, "Fairy": 1 },
    "Water": { "Fire": 2, "Grass": 0.5, "Electric": 1, "Water": 1, "Rock": 2, "Normal": 1, "Fire": 2, "Electric": 1, "Grass": 0.5, "Water": 1, "Rock": 2, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Dragon": 1, "Dark": 1, "Fairy": 1 },
    "Electric": { "Water": 2, "Grass": 0.5, "Electric": 1, "Ground": 0.5, "Normal": 1, "Fire": 1, "Water": 2, "Grass": 0.5, "Electric": 1, "Rock": 1, "Fighting": 1, "Poison": 1, "Ground": 0.5, "Flying": 1, "Psychic": 1, "Bug": 1, "Dragon": 1, "Dark": 1, "Fairy": 1 },
    "Grass": { "Water": 2, "Fire": 0.5, "Grass": 1, "Electric": 1, "Rock": 2, "Normal": 1, "Fire": 0.5, "Electric": 1, "Grass": 1, "Water": 2, "Rock": 2, "Fighting": 1, "Poison": 0.5, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 0.5, "Dragon": 1, "Dark": 1, "Fairy": 1 },
    "Ice": { "Grass": 1, "Fire": 0.5, "Water": 1, "Electric": 1, "Rock": 1, "Normal": 1, "Fire": 0.5, "Grass": 2, "Electric": 1, "Water": 1, "Rock": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Dragon": 2, "Dark": 1, "Fairy": 1 },
    "Fighting": { "Rock": 2, "Ghost": 0.5, "Steel": 1, "Normal": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 1, "Ice": 2, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Dragon": 1, "Dark": 2, "Fairy": 0.5 },
    "Poison": { "Grass": 2, "Ghost": 1, "Steel": 0.5, "Normal": 1, "Fire": 1, "Water": 1, "Electric": 1, "Grass": 2, "Ice": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Dragon": 1, "Dark": 1, "Fairy": 2 },
    "Ground": { "Fire": 1, "Grass": 1, "Electric": 2, "Water": 1, "Rock": 1, "Normal": 1, "Fire": 1, "Grass": 1, "Electric": 2, "Water": 1, "Rock": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Dragon": 1, "Dark": 1, "Fairy": 1 },
    "Flying": { "Grass": 1, "Fire": 1, "Electric": 1, "Water": 1, "Rock": 1, "Normal": 1, "Fire": 1, "Grass": 1, "Electric": 1, "Water": 1, "Rock": 1, "Fighting": 2, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 2, "Dragon": 1, "Dark": 1, "Fairy": 1 },
    "Psychic": { "Grass": 1, "Fire": 1, "Electric": 1, "Water": 1, "Rock": 1, "Normal": 1, "Fire": 1, "Grass": 1, "Electric": 1, "Water": 1, "Rock": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Dragon": 1, "Dark": 1, "Fairy": 1 },
    "Bug": { "Grass": 2, "Fire": 0.5, "Electric": 1, "Water": 1, "Rock": 1, "Normal": 1, "Fire": 0.5, "Grass": 2, "Electric": 1, "Water": 1, "Rock": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Dragon": 1, "Dark": 1, "Fairy": 1 },
    "Dragon": { "Grass": 1, "Fire": 1, "Electric": 1, "Water": 1, "Rock": 1, "Normal": 1, "Fire": 1, "Grass": 1, "Electric": 1, "Water": 1, "Rock": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Dragon": 2, "Dark": 1, "Fairy": 0.5 },
    "Dark": { "Grass": 1, "Fire": 1, "Electric": 1, "Water": 1, "Rock": 1, "Normal": 1, "Fire": 1, "Grass": 1, "Electric": 1, "Water": 1, "Rock": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Dragon": 1, "Dark": 1, "Fairy": 1 },
    "Fairy": { "Grass": 1, "Fire": 1, "Electric": 1, "Water": 1, "Rock": 1, "Normal": 1, "Fire": 1, "Grass": 1, "Electric": 1, "Water": 1, "Rock": 1, "Fighting": 1, "Poison": 1, "Ground": 1, "Flying": 1, "Psychic": 1, "Bug": 1, "Dragon": 1, "Dark": 1, "Fairy": 1 }
};